name: "My Setup Java Version"
description: "Set the latest Java version for the current gradle version found in the project."

outputs:
  java-version:
    description: "Java version set"
    value: ${{ steps.setup-java.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Get the latest java version supported
      id: java-version
      uses: daniele-tentoni/java-version-action@2.0.1

    - name: Setup Java
      id: setup-java
      uses: actions/setup-java@v3.11.0
      with:
        distribution: "adopt"
        java-version: ${{ steps.java-version.outputs.java-version }}
