name: Test Action

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Create default properties file
        run: echo "version=7.3" >> gradle-wrapper.properties

      - name: Run Setup Java Version Step
        id: java-version
        uses: ./

      - name: Check the installed java version
        run: "[[ java --version -eq 17 ]]"
