name: Test Action

on:
  pull_request:
    branches:
      - main
  workflow_call:

env:
  repo-name: gradle-wrapper-example

jobs:
  # Fetch remote repo to get the most recent tag to use to test action.
  fetch:
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.repo-version.outputs.repo }}
      version: ${{ steps.repo-version.outputs.version }}
    steps:
      - name: Fetch remote repo
        id: repo-version
        run: |
          repo=https://github.com/Daniele-Tentoni/${{ env.repo-name }}.git
          echo "::set-output name=repo::$repo"
          v=$(git ls-remote --tags --sort=-v:refname $repo | cut -f 1 | head -n 1)
          echo "::set-output name=version::$v"

  test:
    needs: [fetch]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          path: action

      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository: ${{ needs.fetch.outputs.repo }}
          ref: ${{ needs.fetch.outputs.version }}
          path: ${{ env.repo-name }}

      - name: Run Setup Java Version Step
        id: java-version
        uses: ./action

      - name: Check the installed java version
        if: runner.os != 'Windows'
        run: "[[ ${{ steps.java-version.outputs.java-version }} == 17* ]]"

      # or use command: (Get-Command java | Select-Object -ExpandProperty Version).tostring()
      - name: Check the Java version
        if: runner.os == 'Windows'
        run: |
          $jv = '${{ steps.java-version.outputs.java-version }}'
          if ( $jv.StartsWith("17") ) { exit 0 }
          exit 1
