name: Test Action

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          path: action

      - name: Create default properties file
        run: |
          name=gradle-wrapper-example
          repo=https://github.com/Daniele-Tentoni/$name.git
          v=$(git ls-remote --tags --sort=-v:refname $repo | cut -f 1 | head -n 1)
          git clone $repo
          cd $name
          git checkout $v

      - name: Run Setup Java Version Step
        id: java-version
        uses: ./action

      - name: Check the installed java version
        if: runner.os != 'Windows'
        run: "[[ ${{ steps.java-version.outputs.java-version }} == 17* ]]"

      # or use command: (Get-Command java | Select-Object -ExpandProperty Version).tostring()
      - name: Check the Java version
        if: runner.os == 'Windows'
        run: |
          $jv = '${{ steps.java-version.outputs.java-version }}'
          if ( $jv.StartsWith("17") ) { exit 0 }
          exit 1
