name: Test Action

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Create default properties file
        run: echo "distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.2-bin.zip" >> gradle-wrapper.properties

      - name: Run Setup Java Version Step
        id: java-version
        uses: ./

      - name: Check the installed java version
        run: |
          CUR_JAVA_VERSION=java -version 2>&1 head -1 cut -d'"' -f2 sed 's/^1\.//' cut -d'.' -f1
          "[[ $CUR_JAVA_VERSION -eq 17 ]]"